Procedures/Models/Author.cs
namespace Procedures.Models
{
    public class Author
    {
        public int AuthorId { get; set; }
        public string Name { get; set; }
        public List<Book> Books { get; set; }
    }
}

Procedures/Models/Book.cs
namespace Procedures.Models
{
    public class Book
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public int AuthorId { get; set; }
        public Author Author { get; set; }
    }
}

Procedures/Models/BookViewModel.cs
namespace Procedures.Models
{
    public class BookViewModel
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public int AuthorId { get; set; }
        public string AuthorName { get; set; }
    }
}

Procedures/Models/ErrorViewModel.cs
namespace Procedures.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Procedures/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;

namespace Procedures.Controllers
{
    public class AuthorController : Controller
    {
        private readonly string connectionString = "Data Source=DESKTOP\\MSSQLSERVER1;Initial Catalog=procedures;Integrated Security=True;Trust Server Certificate=True";

        public IActionResult Index()
        {
            List<Author> authors = new List<Author>();
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                SqlCommand command = new SqlCommand("GetAllAuthors", connection);
                command.CommandType = CommandType.StoredProcedure;

                connection.Open();
                SqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    Author author = new Author();
                    author.AuthorId = Convert.ToInt32(reader["AuthorId"]);
                    author.Name = reader["Name"].ToString();
                    authors.Add(author);
                }
                connection.Close();
            }
            return View(authors);
        }

        [HttpPost]
        public IActionResult AddAuthor(Author author)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                SqlCommand command = new SqlCommand("AddAuthor", connection);
                command.CommandType = CommandType.StoredProcedure;

                command.Parameters.AddWithValue("@Name", author.Name);

                connection.Open();
                command.ExecuteNonQuery();
                connection.Close();
            }
            return RedirectToAction("Index");
        }

        public class Author
        {
            public int AuthorId { get; set; }
            public string Name { get; set; }
        }
    }
}

Procedures/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Procedures.Models;
using System.Data;

namespace Procedures.Controllers
{
    public class BookController : Controller
    {
        private readonly string connectionString = "Data Source=DESKTOP\\MSSQLSERVER1;Initial Catalog=procedures;Integrated Security=True;Trust Server Certificate=True";

        public ActionResult Index()
        {
            List<BookViewModel> books = new List<BookViewModel>();
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                SqlCommand command = new SqlCommand("GetBooks", connection);
                command.CommandType = CommandType.StoredProcedure;

                connection.Open();
                SqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    BookViewModel book = new BookViewModel();
                    book.BookId = Convert.ToInt32(reader["BookId"]);
                    book.Title = reader["Title"].ToString();
                    //book.AuthorId = Convert.ToInt32(reader["AuthorId"]);
                    book.AuthorName = reader["AuthorName"].ToString();
                    books.Add(book);
                }
                connection.Close();
            }
            return View(books);
        }

        [HttpPost]
        public ActionResult AddBook(BookViewModel book)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                SqlCommand command = new SqlCommand("AddBook", connection);
                command.CommandType = CommandType.StoredProcedure;

                command.Parameters.AddWithValue("@Title", book.Title);
                command.Parameters.AddWithValue("@AuthorId", book.AuthorId);

                connection.Open();
                command.ExecuteNonQuery();
                connection.Close();
            }
            return RedirectToAction("Index");
        }

        public ActionResult DeleteBook(int bookId)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                SqlCommand command = new SqlCommand("DeleteBook", connection);
                command.CommandType = CommandType.StoredProcedure;

                command.Parameters.AddWithValue("@BookId", bookId);

                connection.Open();
                command.ExecuteNonQuery();
                connection.Close();
            }
            return RedirectToAction("Index");
        }
    }
}

Procedures/Views/Author/Index.cshtml
@model List<Procedures.Controllers.AuthorController.Author>
@{
    ViewBag.Title = "Author List";
}

<h2>Author List</h2>

@if (Model.Count > 0)
{
    <table class="table">
        <tr>
            <th>Author ID</th>
            <th>Name</th>
        </tr>
        @foreach (var author in Model)
        {
            <tr>
                <td>@author.AuthorId</td>
                <td>@author.Name</td>
            </tr>
        }
    </table>
}
else
{
    <p>No authors found.</p>
}

<h2>Add Author</h2>

@using (Html.BeginForm("AddAuthor", "Author", FormMethod.Post))
{
    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Add Author</button>
}

Procedures/Views/Book/Index.cshtml
@model List<Procedures.Models.BookViewModel>

<h2>Book List</h2>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Action</th>
    </tr>
    @foreach (var book in Model)
    {
        <tr>
            <td>@book.Title</td>
            <td>@book.AuthorName</td>
            <td>
                @Html.ActionLink("Delete", "DeleteBook", new { bookId = book.BookId }, new { onclick = "return confirm('Are you sure you want to delete this book?');" })
            </td>
        </tr>
    }
</table>

<h2>Add Book</h2>

@using (Html.BeginForm("AddBook", "Book", FormMethod.Post))
{
    <div class="form-group">
        <label for="Title">Title:</label>
        <input type="text" id="Title" name="Title" class="form-control" />
    </div>
    <div class="form-group">
        <label for="AuthorId">Author ID:</label>
        <input type="text" id="AuthorId" name="AuthorId" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Add Book</button>
}

Procedures/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Procedures</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Procedures.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Author</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Procedures - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>